services:
  - type: web
    name: discord-music-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DISCORD_TOKEN
        sync: false
      - key: COOKIEFILE
        value: cookies.txt
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    healthCheckPath: /health
