services:
  - type: web
    name: discord-music-bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: PORT
        value: 8080